theme: jekyll-theme-minimal

### DIAMOND UHC REVAMP ###
VERSION: 0.0

PATCH NOTES:                                   WRITE EVERYTHING YOU HAVE CODED

MAIN GAME FUNCTIONS: NOT FINISHED
RANKING : NOT FINISHED
RESOURCES DROP: NOT FINISHED
DISGUISE NAME : NOT FINISHED
ANNOUNCE: NOT FINISHED
